### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by jeremieSTC** [Cap-go/capacitor-nativegeocoder#3]
Not sure if it is linked to the plugin or my implementation of it (with TypeScript) but I receive this error when I call NativeGeocoding.forwardGeocode():

Error:  TypeError: Cannot read properties of undefined (reading 'slice')
    at web.ts:105:1
    at async createMap (index.tsx:54:1)

**Comment by riderx** [comment]
Thanks for the report it was a mistake on my side, `1.2.23` fix it :)
