### ISSUE TITLE
Error on Native with certain addresses 

### ISSUE THREAD

**Issue by jongbonga** [Cap-go/capacitor-nativegeocoder#30]
When searching for certain addresses, the forward geocoding works on web but fail on native.

In this example,  `"Cape Town International Airport (CPT), Matroosfontein, Cape Town, South Africa"` worked on Web but fail on native.

<img width="763" alt="Screenshot 2023-07-11 at 18 13 25" src="https://github.com/Cap-go/capacitor-nativegeocoder/assets/12111716/f4c096c9-255e-4de4-8f10-58b775b4c383">

**Comment by riderx** [comment]
This plugin is pure implementation of native feature while in web is google service, that may be the difference

**Comment by jongbonga** [comment]
> This plugin is pure implementation of native feature while in web is google service, that may be the difference

This is not web, it's me debugging the native app with Safari.

**Comment by riderx** [comment]
You said on your original message it work on web but not in native. And i was saying in web the lib use google api not in native that why you can find diff i suppose.
Maybe. i can improve the catch to give more info on the issue

**Comment by jongbonga** [comment]
@riderx Ah sorry, I get it know, apologize for the misunderstanding.
