### ISSUE TITLE
result_type parameter prevents returning any addresses

### ISSUE THREAD

**Issue by jonathan-chin** [Cap-go/capacitor-nativegeocoder#49]
I just tried using this plugin to reverse geocode on web and passed in the required parameters: `latitude`, `longitude`, and `apiKey`. however, it returned 0 addresses. I then manually put the generated url into my browser. with `result_type=street_address`, there are indeed no results, but without that parameter, I get several results. it seems they have types like `bar`, `establishment`, and `store`. they just don't have `street_address`.

is it possible to remove this parameter or at least make it a configurable option?

**Comment by riderx** [comment]
just added as optional param
