### ISSUE TITLE
results do not include formatted_address?

### ISSUE THREAD

**Issue by jonathan-chin** [Cap-go/capacitor-nativegeocoder#50]
I'm examining the results form this plugin and while I get a bunch of address components, there's no `formatted_address` field. when examining the network traffic through web, I see that the response indeed includes `formatted_address` but looking at the source code, I think this plugin doesn't forward that info.

is there a thinking behind this? I could simply reconstruct the formatted address from the address components that are returned, but why not just pass through `formatted_address` if it's already given?

**Comment by jongbonga** [comment]
I don't know if [this](https://github.com/Cap-go/capacitor-nativegeocoder/issues/30#issuecomment-1668867229) help

**Comment by riderx** [comment]
i added to the doc that is not returned to be consistent between platform
